### ISSUE TITLE
One bag from Clients disappears.

### ISSUE THREAD

**Issue by Apryed** [enragedpixel/Carry-Stacker-Reloaded#14]
Issue: If a client grab +1 bags ( 2 or more ) one bag will get lost. This will make some missions impossible to finish if stacking, like Firestarer Day 2 on DS, where you need to get 2 servers. If a client grab both servers, you will need to restart.

Crash log: No error.

Mods running:
Carry Stacker Reloaded <- Yours with a bit of tweaking ( Since Mod Menu didn't showed Up y modified the options.txt to show up )
[WolfHud](https://github.com/Kamikaze94/WolfHUD)
Better Bots
Bot Bullet Collision Fixer
BuilDB
CaseFiles Helper [Hoxton Breakout Day 2]
Civilian ! Marker for Drop-ins
Clear Texture Cache
CreateEmptyLobby
Disable Cam Highlight if not Active
Fading Contour
Filtered Camera Beeps
Full Speed Swarm
Goonmod's Custom Waypoints
Hostage Escort Tweaks
Improved Offline Functionality
Isolation Helper [No Mercy]
Item Hunter
Iter
Keepers
Less Inaccurate Weapon Laser
Meth Helper Updated
ModWorkshop Mod Finder
Monkeepers
Moveable Intimidated Cop
Mr. Dr. Fantastic!
No Dirt Camera
No Duplicated Bullets
OnlyEnabledMods
Pager Contour
Reconnect to server
Search Inventory
SecretAchievementHighlightFilter
Stop the crimespree loss on crash
The Fixes
The Fixes Preventer
TweakdataFixed
VELOSync

System information:
OS: Windows 10 Pro 64 bits
RAM : 1x16 GB RAM DDR4 @ 2666
Graphic Card : RTX 2060 6GB

**Comment by Deodus** [comment]
Conflicts with The Fixes. To fix edit the playermanager.lua in PAYDAY 2\mods\The Fixes\
Remove or comment everything starting from that line: `if not TheFixesPreventer.remove_bag_from_back_playerman then`

**Comment by m-alorda** [comment]
Hi, @Deodus. Thank you for taking the time to find this compatibility issue and post it here!! It seems like `The Fixes` already includes a feature to disable certain fixes within the mod. See [here](https://modworkshop.net/mod/24527).

It seems like that fix woud have to be prevented hooking some code to `core/lib/system/coresystem` such as:
```lua
TheFixesPreventer = TheFixesPreventer or {}
TheFixesPreventer.remove_bag_from_back_playerman = true
```
It would have to be tested.

Also, we would have to explain somehow to users that this mod disables this feature from `The Fixes` (maybe in `README.md`).

If you are willing to make this changes, and create a pull request, I'd be happy to review and accept it. Otherwise, I'll try to change and test it myself when I have the time. 

Again, thumbs up to you, @Deodus :)

**Comment by Apryed** [comment]
Thank you very much. Although I've check and there was an option for such thing in `The Fixes Preventer` to enable or disable, your indications where the ones that enable me to make it work. ;)
